name: Build RetroBudget v2 (debug, split)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # ===== Створюємо ЧИСТИЙ проєкт у підпапці app/ з новим applicationId
      - name: Create Flutter project (new appId)
        run: |
          flutter create app \
            --platforms=android \
            --project-name=retrobudget2 \
            --org com.rb.unique987 \
            --overwrite

      # ===== Додаємо стабільну версію fl_chart, сумісну з Flutter 3.24
      - name: Add dependency fl_chart
        working-directory: app
        run: flutter pub add fl_chart@0.63.0

      # ===== Підміняємо main.dart готовим кодом
      - name: Inject main.dart
        working-directory: app
        run: |
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          import 'package:fl_chart/fl_chart.dart';

          void main() => runApp(const RetroBudgetApp());

          class RetroBudgetApp extends StatelessWidget {
            const RetroBudgetApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Ретро-бюджет v2',
                theme: ThemeData.dark().copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0E1F17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFFFFC94),
                    secondary: Color(0xFFFFB347),
                  ),
                  appBarTheme: const AppBarTheme(backgroundColor: Colors.black),
                  floatingActionButtonTheme: const FloatingActionButtonThemeData(
                    backgroundColor: Color(0xFFFFB347),
                    foregroundColor: Colors.black,
                  ),
                ),
                home: const HomePage(),
              );
            }
          }

          class Expense {
            final String category;
            final double amount;
            Expense(this.category, this.amount);
          }

          class HomePage extends StatefulWidget {
            const HomePage({super.key});
            @override
            State<HomePage> createState() => _HomePageState();
          }

          class _HomePageState extends State<HomePage> {
            double balance = 1000;
            final List<Expense> expenses = [
              Expense("Їжа", 120),
              Expense("Транспорт", 60),
              Expense("Розваги", 90),
            ];

            void _addExpense() {
              showDialog(
                context: context,
                builder: (context) {
                  final categoryController = TextEditingController();
                  final amountController = TextEditingController();
                  return AlertDialog(
                    backgroundColor: Colors.black,
                    title: const Text("Додати витрату"),
                    content: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        TextField(
                          controller: categoryController,
                          decoration: const InputDecoration(labelText: "Категорія"),
                        ),
                        TextField(
                          controller: amountController,
                          decoration: const InputDecoration(labelText: "Сума"),
                          keyboardType: TextInputType.number,
                        ),
                      ],
                    ),
                    actions: [
                      TextButton(
                        child: const Text("Скасувати"),
                        onPressed: () => Navigator.pop(context),
                      ),
                      ElevatedButton(
                        child: const Text("Додати"),
                        onPressed: () {
                          setState(() {
                            final amount = double.tryParse(amountController.text) ?? 0;
                            if (amount > 0 && categoryController.text.isNotEmpty) {
                              expenses.add(Expense(categoryController.text, amount));
                              balance -= amount;
                            }
                          });
                          Navigator.pop(context);
                        },
                      ),
                    ],
                  );
                },
              );
            }

            List<PieChartSectionData> _sections() {
              if (expenses.isEmpty) {
                return [
                  PieChartSectionData(
                    color: Colors.grey.shade700,
                    value: 1,
                    title: "Немає даних",
                    radius: 60,
                    titleStyle: const TextStyle(fontSize: 12, color: Colors.white),
                  ),
                ];
              }
              return List.generate(expenses.length, (i) {
                final e = expenses[i];
                return PieChartSectionData(
                  color: Colors.primaries[i % Colors.primaries.length],
                  value: e.amount,
                  title: "${e.category}\n${e.amount.toStringAsFixed(0)}",
                  radius: 60,
                  titleStyle: const TextStyle(fontSize: 12, color: Colors.white),
                );
              });
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: const Text("Ретро-бюджет v2")),
                body: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("Баланс: ${balance.toStringAsFixed(2)} ₴",
                          style: const TextStyle(fontSize: 20)),
                      const SizedBox(height: 12),
                      Expanded(
                        child: ListView.builder(
                          itemCount: expenses.length,
                          itemBuilder: (context, index) {
                            final e = expenses[index];
                            return ListTile(
                              leading: const Icon(Icons.payments, color: Colors.amber),
                              title: Text(e.category),
                              trailing: Text("-${e.amount.toStringAsFixed(2)} ₴"),
                            );
                          },
                        ),
                      ),
                      const SizedBox(height: 12),
                      SizedBox(
                        height: 220,
                        child: Card(
                          color: const Color(0xFF12231B),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: PieChart(
                              PieChartData(
                                sections: _sections(),
                                centerSpaceRadius: 40,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                floatingActionButton: FloatingActionButton(
                  onPressed: _addExpense,
                  child: const Icon(Icons.add),
                ),
              );
            }
          }
          EOF

      - name: flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build split APKs (debug)
        working-directory: app
        run: flutter build apk --debug --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: retrobudget_v2_apk_debug_split
          path: app/build/app/outputs/flutter-apk/*.apk
