name: Build Android APK (installable)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Create Flutter project
        run: |
          flutter create . --platforms=android --project-name retro_budget --org com.rb.unique123 --overwrite

      - name: Inject minimal app
        run: |
          mkdir -p lib
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          void main() => runApp(const MyApp());
          class MyApp extends StatelessWidget {
            const MyApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Retro Budget',
                theme: ThemeData.dark(useMaterial3: true).copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0F1E17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFC49A41), secondary: Color(0xFF557153),
                  ),
                ),
                home: Scaffold(
                  appBar: AppBar(title: const Text('Розподіл коштів')),
                  body: const Center(child: Text('Баланс (демо)', style: TextStyle(fontSize: 22))),
                  floatingActionButton: FloatingActionButton.extended(
                    onPressed: null, label: Text('Додати'), icon: Icon(Icons.add)),
                ),
              );
            }
          }
          EOF

      # Примусово задаємо УНІКАЛЬНИЙ applicationId, щоб не було конфлікту з уже встановленими
      - name: Set unique applicationId
        run: |
          sed -i 's/applicationId "com.rb.unique123.retro_budget"/applicationId "com.rb.myretroapp123"/' android/app/build.gradle || true
          perl -0777 -pe 's/applicationId "[^"]+"/applicationId "com.rb.myretroapp123"/' -i android/app/build.gradle || true

      - name: flutter pub get
        run: flutter pub get

      # Створимо APK-и для кожної архітектури — обери arm64-v8a на телефоні
      - name: Build split APKs
        run: flutter build apk --debug --split-per-abi

      - uses: actions/upload-artifact@v4
        with:
          name: retro_apk_split
          path: build/app/outputs/flutter-apk/*.apk
