name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # або 3.22–3.24, будь-яка актуальна

      - name: Create Flutter project
        run: |
          flutter create . --platforms=android --project-name retro_budget --org com.retro.budget --overwrite

      - name: Inject minimal app
        run: |
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          void main() => runApp(const MyApp());
          class MyApp extends StatelessWidget {
            const MyApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Retro Budget',
                theme: ThemeData.dark(useMaterial3: true).copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0F1E17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFC49A41), secondary: Color(0xFF557153),
                  ),
                ),
                home: Scaffold(
                  appBar: AppBar(title: const Text('Розподіл коштів')),
                  body: const Center(child: Text('Баланс (демо)', style: TextStyle(fontSize: 22))),
                  floatingActionButton: FloatingActionButton.extended(
                    onPressed: null, label: Text('Додати'), icon: Icon(Icons.add)),
                ),
              );
            }
          }
          EOF

      - name: Install deps
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk
          path: build/app/outputs/flutter-apk/app-debug.apk
