name: Build Android APK (no downloads needed)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Create Flutter project
        run: |
          flutter create . --platforms=android --project-name retro_budget --org com.retro.budget --overwrite

      - name: Inject app source (pubspec + main.dart)
        run: |
          cat > pubspec.yaml << 'EOF'
          name: retro_budget
          description: Мінімальний застосунок для збірки APK
          publish_to: "none"
          version: 0.0.1+1
          environment:
            sdk: ">=3.4.0 <4.0.0"
          dependencies:
            flutter:
              sdk: flutter
            cupertino_icons: ^1.0.6
          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^4.0.0
          flutter:
            uses-material-design: true
          EOF

          mkdir -p lib
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';

          void main() => runApp(const RetroBudgetDemo());

          class RetroBudgetDemo extends StatelessWidget {
            const RetroBudgetDemo({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Retro Budget',
                theme: ThemeData.dark(useMaterial3: true).copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0F1E17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFC49A41),
                    secondary: Color(0xFF557153),
                  ),
                ),
                home: const _Home();
              );
            }
          }

          class _Home extends StatelessWidget {
            const _Home();
            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: const Text('Розподіл коштів')),
                body: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Container(
                        width: 200, height: 200,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          border: Border.all(color: Theme.of(context).colorScheme.primary, width: 12),
                        ),
                        child: const Center(child: Text('Баланс', style: TextStyle(fontSize: 22))),
                      ),
                      const SizedBox(height: 16),
                      const Text('Іконки категорій з % (демо)'),
                      const SizedBox(height: 24),
                      ElevatedButton(onPressed: (){}, child: const Text('Заплановані (демо)')),
                    ],
                  ),
                ),
                floatingActionButton: FloatingActionButton.extended(
                  onPressed: (){},
                  icon: const Icon(Icons.add),
                  label: const Text('Додати'),
                ),
              );
            }
          }
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk
          path: build/app/outputs/flutter-apk/app-debug.apk
