name: Build Android APK (debug)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Create Flutter project
        run: |
          flutter create . --platforms=android --project-name retro_budget --org com.rb.unique --overwrite

      - name: Inject demo app
        run: |
          mkdir -p lib
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          void main() => runApp(const MyApp());
          class MyApp extends StatelessWidget {
            const MyApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Retro Budget',
                theme: ThemeData.dark(useMaterial3: true),
                home: Scaffold(
                  appBar: AppBar(title: const Text('Розподіл коштів')),
                  body: const Center(child: Text('Баланс (демо)', style: TextStyle(fontSize: 22))),
                ),
              );
            }
          }
          EOF

      - name: flutter pub get
        run: flutter pub get

      - name: Build split APKs (debug)
        run: flutter build apk --debug --split-per-abi

      - uses: actions/upload-artifact@v4
        with:
          name: retro_apk_debug_split
          path: build/app/outputs/flutter-apk/*.apk
