name: Build Android APK (debug, clean)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # 1) Створюємо повний Flutter-проєкт у підпапці app/
      - name: Create Flutter project in subdir
        run: flutter create app --platforms=android --project-name retrobudget --org com.rb.unique123 --overwrite

      # 2) Підміняємо головний екран
      - name: Inject demo main.dart
        run: |
          cat > app/lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          void main() => runApp(const MyApp());
          class MyApp extends StatelessWidget {
            const MyApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Retro Budget',
                theme: ThemeData.dark(useMaterial3: true),
                home: const _Home();
              );
            }
          }
          class _Home extends StatelessWidget {
            const _Home();
            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: const Text('Розподіл коштів')),
                body: const Center(child: Text('Баланс (демо)', style: TextStyle(fontSize: 22))),
              );
            }
          }
          EOF

      # 3) Усі подальші команди — В СЕРЕДИНІ папки app/
      - name: flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build split APKs (debug)
        working-directory: app
        run: flutter build apk --debug --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk_debug_split
          path: app/build/app/outputs/flutter-apk/*.apk
