name: Build Android APK (retro_budget)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Отримати код
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Встановити Java (Temurin 17)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Встановити Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # 4. Caching (швидше)
      - name: Flutter pub get
        run: flutter pub get

      # 5. Зібрати release APK (split ABI)
      - name: Build APK (split)
        run: flutter build apk --release --split-per-abi

      # 6. Завантажити артефакти
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk_split
          path: build/app/outputs/flutter-apk/*.apk
