name: Build Android APK (debug, MVP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Отримати код з репозиторію
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Встановити Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Встановити Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # 4. Створити Flutter-проєкт у підкаталозі app
      - name: Create Flutter project in subdir
        run: flutter create app --platforms=android --project-name retrobudget --org com.rb.unique123 --overwrite

      # 5. Додати сумісну версію fl_chart
      - name: Add fl_chart dependency compatible with Flutter 3.24
        working-directory: app
        run: flutter pub add fl_chart:0.64.0

      # 6. Додати твій код програми
      - name: Inject demo main.dart
        run: |
          cat > app/lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';

          void main() => runApp(const RetroBudgetApp());

          class RetroBudgetApp extends StatelessWidget {
            const RetroBudgetApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Ретро-бюджет',
                theme: ThemeData.dark().copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0E1F17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFFFFC94),
                    secondary: Color(0xFFFFB347),
                  ),
                ),
                home: const HomePage(),
              );
            }
          }

          class HomePage extends StatefulWidget {
            const HomePage({super.key});
            @override
            State<HomePage> createState() => _HomePageState();
          }

          class _HomePageState extends State<HomePage> {
            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(
                  title: const Text("Ретро-бюджет"),
                  backgroundColor: Colors.black,
                ),
                body: const Center(
                  child: Text(
                    "Привіт! Це демо-екран.",
                    style: TextStyle(fontSize: 20),
                  ),
                ),
              );
            }
          }
          EOF

      # 7. Завантажити залежності
      - name: flutter pub get
        working-directory: app
        run: flutter pub get

      # 8. Зібрати split-APK
      - name: Build split APKs (debug)
        working-directory: app
        run: flutter build apk --debug --split-per-abi

      # 9. Завантажити артефакти
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk_debug_split
          path: app/build/app/outputs/flutter-apk/*.apk
