name: Build Retro APK (auto-create project)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Отримати код
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Встановити Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Встановити Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # 4. Якщо нема Flutter-проекту — створити його
      - name: Ensure Flutter project exists
        run: |
          set -e
          if [ ! -f "pubspec.yaml" ]; then
            echo "⚙️ Створюю новий Flutter-проект у корені..."
            flutter create . --platforms=android --project-name retrobudget
          fi
          if [ ! -d "android" ]; then
            echo "📁 Додаю Android платформу..."
            flutter create . --platforms=android
          fi

      # 5. Оновити залежності
      - name: Flutter pub get
        run: flutter pub get

      # 6. Зібрати APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # 7. Завантажити результат
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk_release_split
          path: build/app/outputs/flutter-apk/*.apk
