name: Build Android APK (release, modern embedding)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable
          cache: true

      - name: Verify project structure
        run: |
          echo "Checking repo root..."
          ls -la
          test -f pubspec.yaml || { echo "❌ pubspec.yaml not found!"; exit 1; }
          echo "✅ pubspec.yaml found"

      - name: Ensure Android folder exists
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          else
            echo "✅ android/ exists"
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Patch Android Gradle & Kotlin
        shell: bash
        run: |
          set -e
          if [ -f "android/build.gradle" ]; then
            sed -i 's/ext\.kotlin_version\s*=.*$/ext.kotlin_version = "1.9.24"/' android/build.gradle || true
          fi
          if [ -f "android/gradle/wrapper/gradle-wrapper.properties" ]; then
            sed -i 's/gradle-[0-9.]\+/gradle-8.7/g' android/gradle/wrapper/gradle-wrapper.properties || true
          fi

      - name: Migrate to new Flutter Android embedding (v2)
        run: |
          if grep -r "io.flutter.app.FlutterActivity" android/app/src/main/java; then
            echo "Migrating old embedding → v2..."
            find android/app/src/main/java -type f -name "*.java" -exec sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' {} +
          else
            echo "✅ Using modern embedding already"
          fi

      - name: Build APK (split per ABI, release)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retro_apk_release
          path: build/app/outputs/flutter-apk/*-release.apk
