name: Build RetroBudget v2 (debug, split)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Create Flutter project
        run: |
          flutter create app \
            --platforms=android \
            --project-name=retrobudget2 \
            --org com.rb.unique987 \
            --overwrite

      - name: Add dependency fl_chart
        working-directory: app
        run: flutter pub add fl_chart@0.63.0

      - name: Replace main.dart
        working-directory: app
        run: |
          cat > lib/main.dart << 'EOF'
          import 'package:flutter/material.dart';
          import 'package:fl_chart/fl_chart.dart';

          void main() => runApp(const RetroBudgetApp());

          class RetroBudgetApp extends StatelessWidget {
            const RetroBudgetApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'Ретро-бюджет v2',
                theme: ThemeData.dark().copyWith(
                  scaffoldBackgroundColor: const Color(0xFF0E1F17),
                  colorScheme: const ColorScheme.dark(
                    primary: Color(0xFFFFFC94),
                    secondary: Color(0xFFFFB347),
                  ),
                  appBarTheme: const AppBarTheme(backgroundColor: Colors.black),
                ),
                home: const HomePage(),
              );
            }
          }

          class Expense {
            final String category;
            final double amount;
            Expense(this.category, this.amount);
          }

          class HomePage extends StatefulWidget {
            const HomePage({super.key});
            @override
            State<HomePage> createState() => _HomePageState();
          }

          class _HomePageState extends State<HomePage> {
            double balance = 1000;
            final List<Expense> expenses = [
              Expense("Їжа", 120),
              Expense("Транспорт", 60),
              Expense("Розваги", 90),
            ];

            void _addExpense() {
              showDialog(
                context: context,
                builder: (context) {
                  final catCtrl = TextEditingController();
                  final amtCtrl = TextEditingController();
                  return AlertDialog(
                    title: const Text("Додати витрату"),
                    content: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        TextField(controller: catCtrl, decoration: const InputDecoration(labelText: "Категорія")),
                        TextField(controller: amtCtrl, decoration: const InputDecoration(labelText: "Сума"), keyboardType: TextInputType.number),
                      ],
                    ),
                    actions: [
                      TextButton(onPressed: ()=>Navigator.pop(context), child: const Text("Скасувати")),
                      ElevatedButton(
                        onPressed: (){
                          setState(() {
                            final amt = double.tryParse(amtCtrl.text) ?? 0;
                            if(amt>0 && catCtrl.text.isNotEmpty){
                              expenses.add(Expense(catCtrl.text, amt));
                              balance -= amt;
                            }
                          });
                          Navigator.pop(context);
                        },
                        child: const Text("Додати"),
                      ),
                    ],
                  );
                },
              );
            }

            List<PieChartSectionData> _sections() {
              if (expenses.isEmpty) {
                return [PieChartSectionData(color: Colors.grey, value: 1, title: "Немає даних")];
              }
              return List.generate(expenses.length, (i) {
                final e = expenses[i];
                return PieChartSectionData(
                  color: Colors.primaries[i % Colors.primaries.length],
                  value: e.amount,
                  title: "${e.category}\n${e.amount.toStringAsFixed(0)}",
                  radius: 60,
                  titleStyle: const TextStyle(fontSize: 12, color: Colors.white),
                );
              });
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: const Text("Ретро-бюджет v2")),
                body: Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(12),
                      child: Text("Баланс: ${balance.toStringAsFixed(2)} ₴", style: const TextStyle(fontSize: 20)),
                    ),
                    Expanded(child: ListView(
                      children: expenses.map((e)=>ListTile(
                        leading: const Icon(Icons.money, color: Colors.amber),
                        title: Text(e.category),
                        trailing: Text("-${e.amount.toStringAsFixed(2)} ₴"),
                      )).toList(),
                    )),
                    SizedBox(height:220,child: PieChart(PieChartData(sections:_sections(),centerSpaceRadius:40))),
                  ],
                ),
                floatingActionButton: FloatingActionButton(onPressed:_addExpense,child:const Icon(Icons.add)),
              );
            }
          }
          EOF

      - name: flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build split APKs (debug)
        working-directory: app
        run: flutter build apk --debug --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: retrobudget_v2_apk_debug_split
          path: app/build/app/outputs/flutter-apk/*.apk
